"""add answers table

Revision ID: a6c20669e892
Revises: d60e349a22f4
Create Date: 2024-05-12 16:17:16.351661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c20669e892'
down_revision = 'd60e349a22f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_user_id'))
        batch_op.drop_index(batch_op.f('ix_answer_timestamp'))
        batch_op.drop_index(batch_op.f('ix_answer_question_id'))

    op.drop_table('answer')
    # ### end Alembic commands ###
